source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'pg'
gem 'jquery-rails'
gem 'devise'
gem 'sendgrid'
gem 'country-select', '~> 1.1.1'
gem 'carrierwave'
gem 'rmagick'
gem 'fog'
gem 'fancybox-rails'
gem 'haml-rails'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'exception_notification'
gem 's3_direct_rails'
gem 'formtastic', '~> 2.1.1'
gem 'activeadmin', "~> 0.4.3"
gem 'ayah_integration'
gem 'mime-types', :require => 'mime/types'
gem 'simple_form'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'compass-rails'
end

group :development, :test do
  gem 'bullet'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'ffaker'
  gem 'fixture_builder'
  gem 'heroku'
  gem 'heroku_san'
  gem 'taps'
  gem 'ruby-debug19'
  gem 'rspec-rails'
  gem 'poltergeist'
  gem 'shoulda'
  gem 'sqlite3'
end
