source 'https://rubygems.org'

gem 'activeadmin'
gem 'airbrake'
gem 'american_date'
gem 'bitly'
gem 'cancan'
gem 'carrierwave'
gem 'country-select', '~> 1.1.1'
gem 'devise'
gem 'fancybox-rails'
gem 'fog'
gem 'jquery-rails'
gem 'kaminari'
gem 'haml-rails'
gem 'mime-types', require: 'mime/types'
gem 'mini_magick'
gem 'pg'
gem 'rails', '3.2.12'
gem 'simple_form'
gem 'thin-rails'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'compass-rails'
  gem 'jquery-fileupload-rails'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'bullet'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'ffaker'
  gem 'fixture_builder'
  gem 'heroku'
  gem 'heroku_san'
  gem 'poltergeist'
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'sqlite3'
  gem 'taps'
  gem 'valid_attribute'
end
