#
# Format:
# 
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: music-mogul
  stack: cedar
  tag: production/*
  config: &default_config
    RAILS_ENV: production
    RACK_ENV: production
    BUNDLE_WITHOUT: "development:test"
    AWS_ACCESS_KEY_ID: AKIAIAZHJIZGTW6R55AQ
    AWS_SECRET_ACCESS_KEY: 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
    AWS_BUCKET: music-mogul-production
  addons:
    - sendgrid:starter
    - heroku-postgresql:dev

staging:
  app: music-mogul-staging
  stack: cedar
  tag: staging/*
  config:
    <<: *default_config
    RAILS_ENV: staging
    RACK_ENV: staging
    AWS_ACCESS_KEY_ID: AKIAIAZHJIZGTW6R55AQ
    AWS_SECRET_ACCESS_KEY: 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
    AWS_BUCKET: music-mogul-staging
  addons:
    - sendgrid:starter
    - heroku-postgresql:dev
